POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user1@user.com",
    "password": "123456"
}

###
GET http://localhost:3000/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidXNlcjFAdXNlci5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NjE4NTQ2NTUsImV4cCI6MTY2MTg1NDcxNX0.IdLOZKa_GXd5wfO9fZFmitXKWa057F08L0g5G1RQnhI

#https 

#{role: 'user'}
